openapi: 3.0.0

info:
  title: My API
  version: 1.0.0
  description: User API with complex data types

servers:
  - url: http://localhost:3000

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1

        name:
          type: string
          example: Manoj

        age:
          type: integer
          example: 25

        isActive:
          type: boolean
          example: true

        skills:
          type: array
          items:
            type: string
          example: ["Node.js", "React", "MongoDB"]

        address:
          type: object
          properties:
            city:
              type: string
              example: Bangalore
            pincode:
              type: integer
              example: 560001

    Error:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: Error message

paths:
  /users:
    get:
      summary: Get all users
      description: Fetch all users with detailed data

      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
              example:
                - id: 1
                  name: Manoj
                  age: 25
                  isActive: true
                  skills: ["Node.js", "React"]
                  address:
                    city: Bangalore
                    pincode: 560001

                - id: 2
                  name: Kumar
                  age: 28
                  isActive: false
                  skills: ["Java", "Spring"]
                  address:
                    city: Mysore
                    pincode: 570001

                - id: 3
                  name: Jabez
                  age: 22
                  isActive: true
                  skills: ["Python", "Java"]
                  address:
                    city: Delhi
                    pincode: 110001

        404:
          description: No users found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users:
    post:
      summary: Create user
      description: Add a new user

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
            example:
              name: Rahul
              age: 22
              isActive: true
              skills: ["Python"]
              address:
                city: Delhi
                pincode: 110001

      responses:
        201:
          description: User created successfully